### ISSUE TITLE
データベースマイグレーションツールの導入

### ISSUE THREAD

**Issue by okeysea** [KeisukeKometani/online_shop#5]
手動でテーブルを作るのが面倒なので、自動でよしなにやってくれるように変更したい。

検討package

- [golang-migrate/migrate](https://github.com/golang-migrate/migrate)
- [goose](https://bitbucket.org/liamstask/goose/src/master/)
- [sql-migrate](https://github.com/rubenv/sql-migrate)

**Comment by okeysea** [comment]
とりあえず、よくわからないので、golang-migrate/migrateでいきます！

**Comment by KeisukeKometani** [comment]
OKです。

**Comment by okeysea** [comment]
@KeisukeKometani 
- [golang-migrate/migrate](https://github.com/golang-migrate/migrate)を使ってプルリクしました！
